### ISSUE TITLE
Remove radius normalisation in station keeping?

### ISSUE THREAD

**Issue by tsaoyu** [WRSC/rules#12]
The rule on station keeping currently normalise the radius of each boat based on its length. I doubt if we should keep doing this in WRSC 2019 as the normalisation seems give too much advantage to longer boats.

| Team  | Initial Radius | Length | Normalised Radius| 
| ------------- | ------------- | -------|-----|
| Aber | 12.59 | 1.3 | 9.68 | 
| Soton  | 13.26 | 1.0 | 13.26 |
| Difference (Aber-Soton) | 5.3%    |  30%     |     36.98%      |

Taking the competition result from last year as an example, in micro-sailboat class, team Aberystwyth (Aber) achieved a normalised radius at 9.68 metres with their 1.3 metres boat. Team Southampton (Soton) has an normalised radius at 13.26 metres with a 1 metre long boat. The total advantage Aber over Soton is (1+5.3%)(1+30%) = 1 + 36.98% which means the length itself contribute more than 30% in the final grade. 

Similar example can also be found in between ENSTA and Shanghai.

| Team  | Initial Radius | Length | Normalised Radius| 
| ------------- | ------------- | -------|-----|
| ENSTA-1 | 14.30 | 2.6 | 9.68 | 
| Shanghai-3  | 14.90| 1.5 | 13.26 |
| Difference (ENSTA-Shanghai) | 4.1%    |  73%     |     80.54%      |

Team ENSTA can take advantage of the normalisation by more than 73% precent. Does a 2.6 metres long boat is 73% harder to control than the 1.5 metres one? If not I think the normalisation had given too much advantage to the longer boat, not to mention the smaller boat is actually more difficult to control due to its Froude number.

**Comment by takluyver** [comment]
I guess part of the idea is that if the GPS receiver is mounted near the bow or the stern, simply turning a bigger boat will already move the receiver. Also, the competition tracker might be further from the team's own GPS.

But I agree that simply dividing by length probably over-corrects for that. We might want to be cautious about removing the correction entirely, since we have one of the smaller boats, people might think we're trying to skew the scoring in our favour. Maybe we should do some modelling to come up with a better correction.

**Comment by Nanoseb** [comment]
Ah, I didn't consider the position of the GPS, that's a good point.
In that case subtracting the boat length to the radius could correct for that.

Concerning a modelling I am not sure what to model in such case. 
Not directly related, but I think the correction should be kept as simple as possible and not become a black box if we try to take too many variables into account.

(@tsaoyu maybe you should mention that rules are being discussed here on the ML, because for now I think we are the only one monitoring this repository)

**Comment by colinsauze** [comment]
Copying onto here what I just sent on the WRSC mailing list:

I don't see any problem with removing this normalisation. I'm not sure i'm even convinced by the whole idea that the smaller boat is more maneuverable, often the small boats struggle to steer against the wind and the tide and will be slower moving. If anything these results show that there isn't any practical difference.

**Comment by smaria** [comment]
I agree with Colin and Tony. Both smaller and longer boats have factors that will make their results worse. Trying to compensate fairly not only needs complex formulas. The compensation also makes the outcome unclear for an observer and meaningless for the scientific application that this challenge was designed for. 
In the end, is up to the teams to place the GPS on their boat and choose their boat length. Speaking as someone who doesn't currently have a competing boat ;-)

**Comment by tsaoyu** [comment]
Boat length based radius normalisation is now removed in WRSC 2019 rule.
